# MuCloud Bot Python配置文件
account: # 账号相关
  user_id: 123456  # QQ账号（留空则自动获取）
  nick_name: "" #昵称（留空则自动获取）
  bot_admin: []

api: # Api设置
  host: '127.0.0.1'
  port: 5700

server: # 监听服务器设置
  host: '127.0.0.1'
  port: 5701

thread_pool: # 线程池最大线程数
  max_workers: 5

qq_data_cache: # QQ数据缓存设置
  expire_time: 300  # 缓存过期时间（秒）