#配置文件

#账号
account: # 账号相关
  user_id:    # QQ账号（留空则自动获取）
  nick_name: "" #昵称（留空则自动获取）
  bot_admin: [3569709728,403253,3876750974]

#网络
api: # Api设置
  host: '127.0.0.1'
  port: 5700

server: # 监听服务器设置
  host: '127.0.0.1'
  port: 5701
  
#其他
thread_pool: 
  max_workers: 12 # 线程池最大线程数

qq_data_cache:  # QQ数据缓存设置
  enable: true  # 是否启用缓存（非常不推荐关闭缓存，对于对于需要无缓存的场景，推荐在插件内自行调用api来获取而非关闭此配置项）
  expire_time: 300  # 缓存过期时间（秒）
  max_cache_size: 500  # 最大缓存数量（设置过大可能会导致报错）


debug: # 调试模式
  enable: false # 是否启用调试模式

auto_restart_onebot:  # 在Onebot实现端状态异常时自动重启Onebot实现端（需开启心跳包）
  enable: true  # 是否启用自动重启

command:  # 命令相关
  command_start: "*"  # 命令起始符

auto_check_update: #自动更新（仅启动时检测）
  enable: false #是否启用
  auto_download: true #是否自动下载